spring:
  application:
#    修改应用的名字
    name: eureka123

eureka:
  client:
    service-url:
#      指定注册中心的注册地址
      defaultZone: http://localhost:8761/eueka/
#      自动向注册中心注册开关,默认true
    register-with-eureka: false
  server:
#    关闭自我保护模式(开发环境下关闭,生产环境开启)
    enable-self-preservation: false
server:
  port: 8761
